---
pages:
- index.md
hide_body: false
is_partial: false
fields:
- type: file
  name: image
  label: Image
  default: "/uploads/2018/04/24/feature.jpg"
- type: text
  label: Page title
  name: title
- type: text
  name: excerpt
  label: Page description
- type: field_group
  fields:
  - type: text
    name: title
    label: Title
  - type: textarea
    name: body
    label: Body
    config:
      wysiwyg: true
      schema:
        format: markdown
  - type: tag_list
    name: items
    label: List items
  label: Approach section
  name: approach
- type: field_group
  name: vision
  label: Vision section
  fields:
  - type: text
    name: title
    label: Title
  - type: textarea
    name: body
    label: Body
    config:
      wysiwyg: true
      schema:
        format: markdown
- type: field_group
  name: services
  label: Services section
  fields:
  - type: text
    name: title
    label: Title
  - type: textarea
    name: body
    label: Body
    config:
      wysiwyg: true
      schema:
        format: markdown
  - type: field_group_list
    name: items
    label: Services
    fields:
    - type: text
      name: title
      label: Title
    - type: textarea
      name: content
      label: Content
      config:
        wysiwyg: true
        schema:
          format: markdown
    config:
      labelField: title
- type: field_group
  name: testimonial
  label: Testimonial section
  fields:
  - type: text
    name: title
    label: Title
  - type: textarea
    name: body
    label: Body
    config:
      wysiwyg: true
      schema:
        format: markdown
- type: field_group
  name: partners
  label: Partners section
  fields:
  - type: text
    name: title
    label: Title
  - type: field_group_list
    name: items
    label: Partners
    fields:
    - type: file
      name: image
      label: Image
    - type: textarea
      name: content
      label: Content
      config:
        wysiwyg: true
        schema:
          format: markdown
    - type: text
      name: linkedin_link
      label: LinkedIn link
    config:
      labelField: content
- type: field_group
  name: contact
  label: Contact
  fields:
  - type: text
    name: title
    label: Title
  - type: textarea
    name: body
    label: Content
    config:
      wysiwyg: true
      schema:
        format: markdown
